apiVersion: v1
kind: Pod
metadata:
  name: failing-pod
  namespace: test-apps
spec:
  containers:
  - name: failing-container
    image: non-existent-image:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  restartPolicy: Never
